COMP = gcc
FLAGS = -Wall -o
OBJS = main.c myTerm.c ../lab1/mySimpleComputer.c

.PHONY: clean run all

all: main

main:
	$(COMP) $(OBJS) $(FLAGS) main.exe

#-include *.d

#main: main.o
#	gcc -c main.o 

#main.o: main.c
#	gcc -o main.c 
